Add support for login to Docker registry
stackhpc/ansible-collection-hashicorp pull request #12
Opened 2022-03-07 17:28 UTC by oneswig

Perform a Docker registry login before container pull, if credentials
are defined (for the Consul container, but applicable to both).

2022-03-08 08:45 UTC, markgoddard requested changes

2022-03-08 08:45 UTC, markgoddard commented on roles/vault/README.md
> +      * `registry_password`: Password for login to private Docker registry (default: Omitted)
Should these be top-level variables, given that they aren't specific to the consul container?

Also, missing `registry_url`.

2022-03-08 08:45 UTC, markgoddard commented on roles/vault/README.md
> +      * `etc_hosts`: Dict of `{<hostname>:<ip_address>}` to be added to container /etc/hosts (default: Omitted)
It's on L19

2023-08-02 08:33 UTC, mnasiadka commented
Closing in favour of https://github.com/stackhpc/ansible-collection-hashicorp/pull/49

2023-08-02 08:33 UTC, closed without merging